# Generated by Django 5.1.1 on 2025-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='brand',
        ),
        migrations.AddField(
            model_name='laptop',
            name='title',
            field=models.CharField(default='Default Laptop', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(max_length=255),
        ),
    ]
