# Generated by Django 5.1.5 on 2025-01-24 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_laptop_owner_alter_laptop_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='title',
            field=models.CharField(default='Default Laptop', max_length=100),
        ),
    ]
